// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using yesterdayinspace.Models;

namespace yesterdayinspace.Migrations
{
    [DbContext(typeof(YISContext))]
    [Migration("20181220194752_SocialLinks")]
    partial class SocialLinks
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("yesterdayinspace.Models.APContent", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.HasKey("ID");

                    b.ToTable("APContent");
                });

            modelBuilder.Entity("yesterdayinspace.Models.CCEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AltRole");

                    b.Property<string>("BioImg");

                    b.Property<string>("BioText");

                    b.Property<string>("Name");

                    b.Property<string>("Role");

                    b.Property<string>("ThumbImg");

                    b.Property<string>("Type");

                    b.HasKey("ID");

                    b.ToTable("CCEntity");
                });

            modelBuilder.Entity("yesterdayinspace.Models.GPContent", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Caption");

                    b.Property<string>("ThumbURL");

                    b.Property<string>("Type");

                    b.Property<string>("URL");

                    b.HasKey("ID");

                    b.ToTable("GPContent");
                });

            modelBuilder.Entity("yesterdayinspace.Models.HPContent", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Section");

                    b.Property<string>("Title");

                    b.Property<string>("URL");

                    b.HasKey("ID");

                    b.ToTable("HPContent");
                });
#pragma warning restore 612, 618
        }
    }
}
