// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using yesterdayinspace.Models;

namespace yesterdayinspace.Migrations
{
    [DbContext(typeof(YISContext))]
    [Migration("20190311032852_MusicUpdate4")]
    partial class MusicUpdate4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("yesterdayinspace.Models.APContent", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.HasKey("ID");

                    b.ToTable("APContent");
                });

            modelBuilder.Entity("yesterdayinspace.Models.CCEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AltRole");

                    b.Property<string>("BioImg");

                    b.Property<string>("BioText");

                    b.Property<string>("Name");

                    b.Property<string>("Role");

                    b.Property<string>("Social1Display");

                    b.Property<string>("Social1Type");

                    b.Property<string>("Social1URL");

                    b.Property<string>("Social2Display");

                    b.Property<string>("Social2Type");

                    b.Property<string>("Social2URL");

                    b.Property<string>("Social3Display");

                    b.Property<string>("Social3Type");

                    b.Property<string>("Social3URL");

                    b.Property<string>("Social4Display");

                    b.Property<string>("Social4Type");

                    b.Property<string>("Social4URL");

                    b.Property<string>("Social5Display");

                    b.Property<string>("Social5Type");

                    b.Property<string>("Social5URL");

                    b.Property<string>("ThumbImg");

                    b.Property<string>("Type");

                    b.HasKey("ID");

                    b.ToTable("CCEntity");
                });

            modelBuilder.Entity("yesterdayinspace.Models.GPContent", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Caption");

                    b.Property<string>("ThumbURL");

                    b.Property<string>("Type");

                    b.Property<string>("URL");

                    b.HasKey("ID");

                    b.ToTable("GPContent");
                });

            modelBuilder.Entity("yesterdayinspace.Models.HPContent", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Caption");

                    b.Property<string>("Section");

                    b.Property<string>("Social");

                    b.Property<string>("Thumb");

                    b.Property<string>("Title");

                    b.Property<string>("URL");

                    b.HasKey("ID");

                    b.ToTable("HPContent");
                });

            modelBuilder.Entity("yesterdayinspace.Models.MPContent", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BandURL");

                    b.Property<string>("Embed");

                    b.Property<string>("Info");

                    b.Property<string>("SoundURL");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("MPContent");
                });
#pragma warning restore 612, 618
        }
    }
}
