// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using yesterdayinspace.Models;

namespace yesterdayinspace.Migrations
{
    [DbContext(typeof(YISContext))]
    partial class YISContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("yesterdayinspace.Models.CCEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BioImg");

                    b.Property<string>("BioText");

                    b.Property<string>("Name");

                    b.Property<string>("Role");

                    b.Property<string>("ThumbImg");

                    b.Property<string>("Type");

                    b.HasKey("ID");

                    b.ToTable("CCEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
